### ISSUE TITLE
Parse "password" API spec to hide typed passwords

### ISSUE THREAD

**Issue by vykozlov** [ai4os/deepaas_ui#2]
### Problem
User application schema may include "password" String fields to hide typed passwords, currently "deepaas_ui" does not use this information and typed in UI passwords are visible

### Possible solution

In the user code the password field can be configured as

```
password = fields.String(
        required=True,
        validate=validate.Length(min=1),
        load_only=True,
        metadata={
            "description": "password for downloading data.",
            "format": "password",
        },
    )
```
e.g. see real example [here](https://github.com/ai4os-hub/WITOIL-for-iMagine/blob/14d1602f5fcb026064bd76c0ace35bdbdc68a016/api/schemas.py#L168C16-L176C6)

which results in the API spec as:
```
        "parameters": [
          {
            "in": "query",
            "name": "password",
            "required": true,
            "type": "string",
            "minLength": 1,
            "description": "password for downloading data.",
            "format": "password"
          },
```

Swagger interface correctly understands this configuration and hides typed passwords.
The offered "deepaas_ui"/"gradio UI" should also parse this "format" for hiding typed passwords.

**Comment by IgnacioHeredia** [comment]
Fixed in https://github.com/ai4os/deepaas_ui/commit/d94fb36ce2a001398ab071aed4d340fe6f77bef9
